= Ritournelle

A WIP toy language, see link:https://archiloque.net/blog/prog-lang-idea/[here] for some info.

The language is statically typed and it generates Ruby code.

== Syntax example

What you can do with current code:

[source]
----
Int i = 10
Int j = 20
Int k
i.plus(10)
i.plus(j)
Float f = 10.5
Float g = j.to_float()

Float h = g

def Int two()
    return 2
end

Int l = self.two()

def Int add_two(Int number)
    return number.plus(2)
end

def Float add_two(Float number)
    return number.plus(2.0)
end

Int m = self.add_two(10)
Int n = self.add_two(m)

Float o = self.add_two(10.0)
Float p = self.add_two(o)

interface Drawable
  def Void draw()
end

class Circle
  implements Drawable
  Float @x
  Float @y
  Float @radius

  def constructor(Float x, Float y, Float radius)
    @x = x
    @y = y
    @radius = radius
  end

  def Void draw()
  end
end

Drawable d = Circle.new(1.0, 2.0, 3.0)
d.draw
----

== Commands

=== Compile a file

[source,sh]
----
bin/compile examples/simple.rit
----

=== Run a file

[source,sh]
----
bin/run examples/simple.rit.rb
----

=== Run tests

[source,sh]
----
rake test
----

== How it works?

- `Ritournelle::Parser` parse the code and generates elements of `Ritournelle::IntermediateRepresentation`
- One by one the `Ritournelle::IntermediateRepresentation` elements are transformed into Ruby code by their corresponding `Ritournelle::CodeGenerator`
- Each Class and Method is managed by a `Ritournelle::CodeGenerator::Context` to manage it local state

== Contributing

Bug reports and pull requests are welcome on GitHub link:https://github.com/archiloque/ritournelle[at this address].
This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the link:http://contributor-covenant.org[Contributor Covenant] code of conduct.

== License

The code is available as open source under the terms of the GPL v3.

== Code of Conduct

Everyone interacting in the Ritournelle project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the link:https://github.com/archiloque/ritournelle/blob/master/CODE_OF_CONDUCT.md[code of conduct].
