
= Ritournelle

A WIP toy language, see link:https://archiloque.net/blog/prog-lang-idea/[here] for some info.

The language is statically typed and it generates Ruby code.

== Syntax example

What you can do with current code:

[source]
----
Integer i = 10
Integer j = 20
Integer k
i.plus(10)
i.plus(j)
Float f = 10.5
Float g = j.to_float()

Float h = g

def Integer two()
    return 2
end

Integer l = self.two()

def Integer add_two(Integer number)
    return number.plus(2)
end

def Float add_two(Float number)
    return number.plus(2.0)
end

Integer m = self.add_two(10)
Integer n = self.add_two(m)

Float o = self.add_two(10.0)
Float p = self.add_two(o)

interface Drawable
  def Void draw()
end

class Circle
  implements Drawable
  Float @x
  Float @y
  Float @radius

  def constructor(Float x, Float y, Float radius)
    @x = x
    @y = y
    @radius = radius
  end

  def Void draw()
  end
end

Drawable d = Circle.new(1.0, 2.0, 3.0)
d.draw
----

== Commands

=== Compile a file

[source,sh]
----
bin/compile examples/simple.rit
----

The Ruby generated file heavily use link:http://yardoc.org[Yard] annotations, you can run Yard on it to generate a documentation.

=== Run a file

[source,sh]
----
bin/run examples/simple.rit.rb
----

=== Run tests

[source,sh]
----
rake test
----

== Syntax

=== Default types

==== Boolean

[source]
----
Boolean b1 = true
Boolean b2 = false
----

==== Integer

[source]
----
Integer i1 = 2
Integer i2 = i1.plus(2)
Integer i3 = i1.minus(-10)
Float i4 = i1.to_float

Boolean b1 = i1.equal_to(i2)
Boolean b2 = i1.less_than(i2)
Boolean b3 = i1.less_than_or_equal_to(i2)
Boolean b4 = i1.more_than(i2)
Boolean b5 = i1.more_than_or_equal_to(i2)
----

==== Float

[source]
----
Float f1 = 2
Float f2 = f1.plus(2)
Float f3 = f1.minus(3)

Boolean b1 = f1.equal_to(f2)
Boolean b2 = f1.less_than(f2)
Boolean b3 = f1.less_than_or_equal_to(f2)
Boolean b4 = f1.more_than(f2)
Boolean b5 = f1.more_than_or_equal_to(f2)
----

=== Methods

You can skip parenthesis when calling a method without parameters

[source]
----
def Integer add_two(Integer number)
  return number.plus(2)
end

def Void do_nothing()
end
----

=== Classes

[source]
----
class Circle
  Float @x
  Float @y getter
  Float @radius getter setter

  def constructor(Float x, Float y, Float radius)
    @x = x
    @y = y
    @radius = radius
  end

  def Void draw()
  end
end

Circle c = Circle.new(1.0, 2.0, 3.0)
c.y
c.radius = 12
c.draw

----

- Members start with an `@` and must be declared
- Members are private
- `getter` and `setter` creates methods to access the member

=== Interfaces

[source]
----
interface Drawable

  def Void draw()

end

class Circle
  implements Drawable

  …

  def Void draw()
  end
end

Drawable d = Circle.new(1.0, 2.0, 3.0)
----

Interfaces declare methods that should be implemented by classes.

=== Conditional expressions

For the moment only `if` is implemented:

[source]
----
Integer i = 10
Integer j = -20

if i.less_than(j)
  i = 40
end
----

The expression to be evaluated must return a boolean, there is no automatic cast from int or float to boolean.

== How it works?

- `Ritournelle::Parser` parse the code and generates elements of `Ritournelle::IntermediateRepresentation`
- One by one the `Ritournelle::IntermediateRepresentation` elements are transformed into Ruby code by their corresponding `Ritournelle::CodeGenerator`
- Each Class and Method is managed by a `Ritournelle::CodeGenerator::Context` to manage it local state

== Contributing

Bug reports and pull requests are welcome on GitHub link:https://github.com/archiloque/ritournelle[at this address].
This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the link:http://contributor-covenant.org[Contributor Covenant] code of conduct.

== License

The code is available as open source under the terms of the GPL v3.

== Code of Conduct

Everyone interacting in the Ritournelle project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the link:https://github.com/archiloque/ritournelle/blob/master/CODE_OF_CONDUCT.md[code of conduct].
