= Ritournelle

A WIP toy language, see link:https://archiloque.net/blog/prog-lang-idea/[here] for some info.

The language is statically typed and it generates Ruby code.

== Syntax example

[source]
----
Int i
i = 10
Int j
Int k
j = 20
i.plus(10)
i.plus(j)
Float f
f = 10.5
Float g
g = j.to_float()

class Circle
  Float @radius
end
----

== Commands

=== Compile a file

[source,sh]
----
bin/compile examples/simple.rit
----

=== Run a file

[source,sh]
----
bin/run examples/simple.rit.rb
----

=== Run tests

[source,sh]
----
rake test
----

== How it works?

- `Ritournelle::Parser` parse the code and generates elements of `Ritournelle::IntermediateRepresentation`
- One by one the `Ritournelle::IntermediateRepresentation` elements are transformed into Ruby code by their corresponding `Ritournelle::CodeGenerator`
- Each Class and Method is managed by a `Ritournelle::CodeGenerator::Context` to manage it local state

== Contributing

Bug reports and pull requests are welcome on GitHub link:https://github.com/archiloque/ritournelle[at this address].
This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the link:http://contributor-covenant.org[Contributor Covenant] code of conduct.

== License

The code is available as open source under the terms of the GPL v3.

== Code of Conduct

Everyone interacting in the Ritournelle project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the link:https://github.com/archiloque/ritournelle/blob/master/CODE_OF_CONDUCT.md[code of conduct].
