module Ritournelle::IntermediateRepresentation
end

require_relative 'intermediate_representation/base'
require_relative 'intermediate_representation/with_statements'
require_relative 'intermediate_representation/type'
require_relative 'intermediate_representation/callable'

require_relative 'intermediate_representation/abstract_method_declaration'
require_relative 'intermediate_representation/assignment'
require_relative 'intermediate_representation/class_declaration'
require_relative 'intermediate_representation/conditional_expression'
require_relative 'intermediate_representation/constructor_declaration'
require_relative 'intermediate_representation/constructor_call'
require_relative 'intermediate_representation/generic_declaration'
require_relative 'intermediate_representation/interface_declaration'
require_relative 'intermediate_representation/intrinsic_method'
require_relative 'intermediate_representation/member_declaration'
require_relative 'intermediate_representation/method_declaration'
require_relative 'intermediate_representation/method_call'
require_relative 'intermediate_representation/return'
require_relative 'intermediate_representation/variable_declaration'
require_relative 'intermediate_representation/world'
