module Ritournelle::IntermediateRepresentation
end

require_relative 'intermediate_representation/assignment'
require_relative 'intermediate_representation/class'
require_relative 'intermediate_representation/method'
require_relative 'intermediate_representation/method_call'
require_relative 'intermediate_representation/value'
require_relative 'intermediate_representation/variable_declaration'
require_relative 'intermediate_representation/world'
