module Ritournelle::IntermediateRepresentation
end

require_relative 'intermediate_representation/base'
require_relative 'intermediate_representation/with_statements'

require_relative 'intermediate_representation/assignment'
require_relative 'intermediate_representation/class'
require_relative 'intermediate_representation/constructor'
require_relative 'intermediate_representation/constructor_call'
require_relative 'intermediate_representation/intrinsic_method'
require_relative 'intermediate_representation/member'
require_relative 'intermediate_representation/method'
require_relative 'intermediate_representation/method_call'
require_relative 'intermediate_representation/return'
require_relative 'intermediate_representation/variable'
require_relative 'intermediate_representation/world'
